// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAUzjDhCHuZkR62nLdhaPnEDlwA5ATRAc',
    appId: '1:1033628638056:web:b17ae8106bd2f20078d4dd',
    messagingSenderId: '1033628638056',
    projectId: 'primeiroprojeto-b2585',
    authDomain: 'primeiroprojeto-b2585.firebaseapp.com',
    storageBucket: 'primeiroprojeto-b2585.firebasestorage.app',
    measurementId: 'G-S7ZNRN0SHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZpnZ9LS78L0b476jqSYWoRfI1t-Is6pU',
    appId: '1:1033628638056:android:6f152a9fb94dc7c778d4dd',
    messagingSenderId: '1033628638056',
    projectId: 'primeiroprojeto-b2585',
    storageBucket: 'primeiroprojeto-b2585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXvuMQzJv2hwRf6vyTqRv4gm9Pi4GZi8',
    appId: '1:1033628638056:ios:04164b51bb2138c878d4dd',
    messagingSenderId: '1033628638056',
    projectId: 'primeiroprojeto-b2585',
    storageBucket: 'primeiroprojeto-b2585.firebasestorage.app',
    iosBundleId: 'com.example.conexaoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXvuMQzJv2hwRf6vyTqRv4gm9Pi4GZi8',
    appId: '1:1033628638056:ios:04164b51bb2138c878d4dd',
    messagingSenderId: '1033628638056',
    projectId: 'primeiroprojeto-b2585',
    storageBucket: 'primeiroprojeto-b2585.firebasestorage.app',
    iosBundleId: 'com.example.conexaoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAUzjDhCHuZkR62nLdhaPnEDlwA5ATRAc',
    appId: '1:1033628638056:web:66500e9fe198114578d4dd',
    messagingSenderId: '1033628638056',
    projectId: 'primeiroprojeto-b2585',
    authDomain: 'primeiroprojeto-b2585.firebaseapp.com',
    storageBucket: 'primeiroprojeto-b2585.firebasestorage.app',
    measurementId: 'G-4WFR1DN6FD',
  );
}
